"""Initial schema

Revision ID: 628e777783bf
Revises:
Create Date: 2026-06-13 13:00:35.401894

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '628e777783bf'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('senior_citizen', sa.SmallInteger(), nullable=True),
    sa.Column('partner', sa.String(length=5), nullable=True),
    sa.Column('dependents', sa.String(length=5), nullable=True),
    sa.Column('tenure', sa.Integer(), nullable=False),
    sa.Column('phone_service', sa.String(length=5), nullable=True),
    sa.Column('multiple_lines', sa.String(length=20), nullable=True),
    sa.Column('internet_service', sa.String(length=20), nullable=True),
    sa.Column('online_security', sa.String(length=20), nullable=True),
    sa.Column('online_backup', sa.String(length=20), nullable=True),
    sa.Column('device_protection', sa.String(length=20), nullable=True),
    sa.Column('tech_support', sa.String(length=20), nullable=True),
    sa.Column('streaming_tv', sa.String(length=20), nullable=True),
    sa.Column('streaming_movies', sa.String(length=20), nullable=True),
    sa.Column('contract_type', sa.String(length=20), nullable=True),
    sa.Column('paperless_billing', sa.String(length=5), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('monthly_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('churn', sa.Boolean(), nullable=False),
    sa.Column('tenure_bucket', sa.String(length=20), nullable=True),
    sa.Column('spending_category', sa.String(length=20), nullable=True),
    sa.Column('estimated_clv', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('churn_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('risk_tier', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_churn'), 'customers', ['churn'], unique=False)
    op.create_index(op.f('ix_customers_contract_type'), 'customers', ['contract_type'], unique=False)
    op.create_index(op.f('ix_customers_payment_method'), 'customers', ['payment_method'], unique=False)
    op.create_index(op.f('ix_customers_tenure_bucket'), 'customers', ['tenure_bucket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_tenure_bucket'), table_name='customers')
    op.drop_index(op.f('ix_customers_payment_method'), table_name='customers')
    op.drop_index(op.f('ix_customers_contract_type'), table_name='customers')
    op.drop_index(op.f('ix_customers_churn'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
